import "./kaite.scss";
export { default as Switch } from "./Switch.vue";
export { default as Input } from "./Input.vue";
export { default as Button } from "./Button.vue";
export { default as Tabs } from "./Tabs.vue";
export { default as Tab } from "./Tab.vue";
export { default as Input } from "./Input.vue";
export { default as Icon } from "./Icon.vue";
export { default as Dialog } from "./Dialog/Dialog.vue";
export { openDialog as openDialog } from "./Dialog/openDialog";
export { default as kaiteUI } from "./kaiteUI";